version: '2'
services:
  db:
    image: postgres
  web:
    volumes:
      - .:/app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
