# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fcc_id', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('submission_type', models.CharField(max_length=200)),
                ('filer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bureau_name', models.CharField(max_length=200)),
                ('bureau_code', models.CharField(max_length=200)),
                ('fcc_id', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='filing',
            name='proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.Proceeding'),
        ),
    ]
