# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filing',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
