# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0002_auto_20170401_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='contact_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='filer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='submission_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
