# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0003_auto_20170401_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='bureau_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
