# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 03:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0005_auto_20170401_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
