# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 13:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0006_filing_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='proceedings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filing',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='filing',
            name='proceeding',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Proceeding',
        ),
    ]
