# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0008_auto_20170401_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.Filing')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='mention',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filings.Person'),
        ),
    ]
