# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0009_auto_20170402_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='simhash',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
